name: Lint, Build and Test

on:
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Use node
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: Install dependencies
        run: yarn install --pure-lockfile

      - name: Lint
        run: yarn workspaces run lint

      - name: Build
        run: yarn workspaces run build

      - name: Test
        run: yarn workspaces run test
